version: 2

jobs:
  build:
    docker:
      - image: circleci/node:9
      - image: circleci/postgres:10.6
        environment:
          POSTGRES_USER: prime
          POSTGRES_DB: prime-test
    environment:
      DATABASE_URL: 'postgres://prime@localhost:5432/prime-test'
      SESSION_SECRET: 'very-secret'
    steps:
      - checkout
      - run: yarn install --frozen-lockfile
      - run: yarn add tslint-junit-formatter jest-junit -DEW
      - run: yarn run lerna bootstrap
      - run: mkdir -p ./reports/junit
      - run: yarn lint:ci
      - run: yarn compile
      - run: yarn coverage:ci
      - run: yarn test:prettier
      - run: yarn codecov
      - run:
          command: cd packages; for x in */junit.xml; do cp $x "../reports/junit/${x%/junit.xml}.xml"; done; cd ..
          when: always
      - store_test_results:
          path: reports/junit
      - store_artifacts:
          path: reports/junit
