version: 2

jobs:
  build:
    docker:
      - image: circleci/node:9
      - image: circleci/postgres:10.6
        environment:
          POSTGRES_USER: prime
          POSTGRES_DB: prime-test
    steps:
      - checkout
      - run: yarn install --frozen-lockfile
      - run: yarn run lerna bootstrap
      - run: yarn test
        environment:
          DATABASE_URL: 'postgres://prime@localhost:5432/prime-test'
          SESSION_SECRET: 'very-secret'
      - run: yarn codecov
